## **<font color="Red">Tensore</font>**

In [1]:
import torch
arr = torch.rand(5)
print(arr)

tensor([0.7544, 0.3661, 0.3615, 0.5314, 0.7692])


In [2]:
torch.cuda.is_available()

False

In [3]:
x1 = torch.empty(4)
print(x1)

tensor([0., 0., 0., 0.])


In [4]:
x2 = torch.empty(2, 3)
print(x2)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [5]:
x3 = torch.empty(3, 10, 10)
print(x3)

tensor([[[4.5803e-16, 1.7124e-42, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0

In [6]:
y = torch.rand(3, 5)
print(y)

tensor([[0.2415, 0.9808, 0.5639, 0.6600, 0.7967],
        [0.9521, 0.3743, 0.5016, 0.8222, 0.8065],
        [0.3416, 0.7657, 0.6082, 0.0247, 0.2708]])


In [7]:
y = torch.zeros(3, 4)
y

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [8]:
y = torch.ones(2, 3)
print(y)
print(y.dtype)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [9]:
y = torch.ones(3, 4, dtype=torch.int)
print(y)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)


In [10]:
y = torch.ones(3, 4, dtype=torch.double)
print(y)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [11]:
y = torch.ones(3, 4, dtype=torch.float32)
print(y)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [12]:
print(y.size())

torch.Size([3, 4])


In [13]:
arr = torch.tensor([x for x in range(2, 21, 2)])
print(arr)

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])


In [14]:
t1 = torch.rand(2, 3, dtype=torch.float)
t2 = torch.rand(2, 3, dtype=torch.float)
print(t1)
print(t2)

tensor([[0.4151, 0.8337, 0.6394],
        [0.6893, 0.4502, 0.3298]])
tensor([[0.7975, 0.3165, 0.2828],
        [0.8567, 0.2313, 0.6201]])


In [15]:
t = t1.add(t2)
t

tensor([[1.2126, 1.1501, 0.9222],
        [1.5460, 0.6814, 0.9499]])

In [16]:
t1.add_(t2)
t1

tensor([[1.2126, 1.1501, 0.9222],
        [1.5460, 0.6814, 0.9499]])

In [17]:
z = t1 + t2
z

tensor([[2.0101, 1.4666, 1.2049],
        [2.4027, 0.9127, 1.5701]])

In [18]:
z = t1 - t2
z

tensor([[0.4151, 0.8337, 0.6394],
        [0.6893, 0.4502, 0.3298]])

In [19]:
z = t1 / t2
z

tensor([[1.5205, 3.6343, 3.2611],
        [1.8046, 2.9464, 1.5319]])

In [20]:
z = t1 * t2
z

tensor([[0.9670, 0.3640, 0.2608],
        [1.3245, 0.1576, 0.5891]])

In [21]:
z = t1 ** t2
z

tensor([[1.1662, 1.0453, 0.9773],
        [1.4524, 0.9151, 0.9687]])

In [22]:
z = t1 // t2
z

tensor([[1., 3., 3.],
        [1., 2., 1.]])

In [23]:
z = torch.mul(t1, t2)
z

tensor([[0.9670, 0.3640, 0.2608],
        [1.3245, 0.1576, 0.5891]])

In [24]:
z = torch.div(t1, t2)
z

tensor([[1.5205, 3.6343, 3.2611],
        [1.8046, 2.9464, 1.5319]])

In [25]:
ten = torch.rand(5, 7)
ten

tensor([[6.9295e-01, 2.7178e-01, 1.7395e-01, 2.8241e-01, 6.7969e-01, 3.5134e-01,
         5.2846e-01],
        [6.0532e-01, 1.1788e-01, 7.2880e-01, 5.1777e-01, 1.5967e-01, 6.1572e-01,
         1.0705e-01],
        [8.2323e-02, 7.7520e-01, 7.0438e-01, 6.0059e-01, 5.1957e-01, 7.4462e-01,
         8.2489e-01],
        [2.3042e-01, 9.7771e-01, 3.2909e-01, 9.2610e-03, 3.7843e-01, 5.5521e-01,
         2.9506e-01],
        [7.9525e-04, 9.0864e-02, 1.6251e-01, 1.8790e-01, 5.3309e-01, 2.6590e-01,
         7.7190e-01]])

In [26]:
ten[1:3, 1:2]

tensor([[0.1179],
        [0.7752]])

In [27]:
ten[1, 1]

tensor(0.1179)

In [28]:
ten[3, 5].item()  # get actual value

0.5552147626876831

In [29]:
ten = torch.rand(5, 4)
ten

tensor([[0.0481, 0.0306, 0.5066, 0.8194],
        [0.3292, 0.4163, 0.1107, 0.4726],
        [0.8627, 0.4641, 0.3776, 0.4473],
        [0.5605, 0.5282, 0.2217, 0.8277],
        [0.1341, 0.0648, 0.6778, 0.6146]])

In [30]:
ten.view(20)

tensor([0.0481, 0.0306, 0.5066, 0.8194, 0.3292, 0.4163, 0.1107, 0.4726, 0.8627,
        0.4641, 0.3776, 0.4473, 0.5605, 0.5282, 0.2217, 0.8277, 0.1341, 0.0648,
        0.6778, 0.6146])

In [31]:
ten.view(10, 2)

tensor([[0.0481, 0.0306],
        [0.5066, 0.8194],
        [0.3292, 0.4163],
        [0.1107, 0.4726],
        [0.8627, 0.4641],
        [0.3776, 0.4473],
        [0.5605, 0.5282],
        [0.2217, 0.8277],
        [0.1341, 0.0648],
        [0.6778, 0.6146]])

In [32]:
ten.view(-1)

tensor([0.0481, 0.0306, 0.5066, 0.8194, 0.3292, 0.4163, 0.1107, 0.4726, 0.8627,
        0.4641, 0.3776, 0.4473, 0.5605, 0.5282, 0.2217, 0.8277, 0.1341, 0.0648,
        0.6778, 0.6146])

In [33]:
ten.view(-1, 4)

tensor([[0.0481, 0.0306, 0.5066, 0.8194],
        [0.3292, 0.4163, 0.1107, 0.4726],
        [0.8627, 0.4641, 0.3776, 0.4473],
        [0.5605, 0.5282, 0.2217, 0.8277],
        [0.1341, 0.0648, 0.6778, 0.6146]])

### **Conversion Tensor2Numpy and Numpy2Tensor**

In [34]:
import numpy as np

In [35]:
a = torch.ones(5)
print(a, type(a), id(a))

b = a.numpy()   # convert tensor2numpy
print(b, type(b), id(a))

# change will show in both
a.add_(1)
print("Tensor : ", a)
print("Numpy : ", b)

tensor([1., 1., 1., 1., 1.]) <class 'torch.Tensor'> 2100532785136
[1. 1. 1. 1. 1.] <class 'numpy.ndarray'> 2100532785136
Tensor :  tensor([2., 2., 2., 2., 2.])
Numpy :  [2. 2. 2. 2. 2.]


In [36]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)  # convert numpy2tensor
print(b)

a += 1
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [37]:
# if you have CUDA

if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)  # move to GPU
    z = x + y
    z.numpy()  # error : numpy don't have GPU access
    z.to("cpu") # move to CPU

In [38]:
x = torch.ones(5, requires_grad=True)  # calculate gradient in future
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
