In [1]:
import torch

#### **Requires_grad**
- If we calculate the gradient then we have to specify with the help of hyperparameter and use __backward()__ method.

In [2]:
x = torch.rand(3, requires_grad=True)  # requires the gradients
print(x)

y = x + 2
print(y)

z = y*y*2
z = z.mean()
print(z)

z.backward()  # calculate gradient wrt x dz/dx
print(x.grad)

tensor([0.3991, 0.7911, 0.0278], requires_grad=True)
tensor([2.3991, 2.7911, 2.0278], grad_fn=<AddBackward0>)
tensor(11.7719, grad_fn=<MeanBackward0>)
tensor([3.1988, 3.7214, 2.7037])


In [3]:
v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
print(v)
z = y*y*2
print(z)
z.backward(v)
print(x.grad)

tensor([0.1000, 1.0000, 0.0010])
tensor([11.5117, 15.5801,  8.2238], grad_fn=<MulBackward0>)
tensor([ 4.1585, 14.8857,  2.7118])


#### **Prevent to tracking the gradient.**
- x.requires_grad_(False)
- x.detach()
- with torch.no_grad()

In [6]:
# x.requires_grad_(False)
g1 = x.requires_grad_(False)
print(g1)

g2 = x.detach()
print(g2)

print(y)
with torch.no_grad():
    y = x + 2
    print(y)


tensor([0.3991, 0.7911, 0.0278])
tensor([0.3991, 0.7911, 0.0278])
tensor([2.3991, 2.7911, 2.0278], grad_fn=<AddBackward0>)
tensor([2.3991, 2.7911, 2.0278])


In [16]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(5):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)
print(weights)
weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])
tensor([12., 12., 12., 12.])
tensor([15., 15., 15., 15.])
tensor([1., 1., 1., 1.], requires_grad=True)


tensor([0., 0., 0., 0.])

In [17]:
for epoch in range(5):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()   # make gradient zero before next iteration
print(weights)

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([1., 1., 1., 1.], requires_grad=True)


In [21]:
# Optimizer
weights = torch.ones(4, requires_grad = True)
print(weights)

tensor([1., 1., 1., 1.], requires_grad=True)
