In [1]:
import torch

In [2]:
torch.__version__

'2.1.0'

### **scaler and vector** and **MATRIX and TENSOR**
- Note: You might've noticed me using lowercase letters for `scalar` and `vector` and uppercase letters for `MATRIX` and `TENSOR`. This was on purpose. In practice, you'll often see scalars and vectors denoted as lowercase letters such as `y` or `a`. And matrices and tensors denoted as uppercase letters such as `X` or `W`.
- 
You also might notice the names martrix and tensor used interchangably. This is common. Since in PyTorch you're often dealing wit`h torch.Tenso`rs (hence the tensor name), however, the shape and dimensions of what's inside will dictate what it actually i
-
<pre>
    ___________________________________________________________________________________________
    |    <b>Name</b>    |       <b>What is it?</b>       |    <b>Number of dimensions</b>    |   <b>Lower or Upper</b>    |
    |____________|_________________________|____________________________|_____________________|
    |   scaler   |    a single number      |             0              |      Lower(a)       |
    |____________|_________________________|____________________________|_____________________|
    |            | a number with direction |                            |                     |
    |   vector   | but can also have many  |             1              |      Lower(y)       |
    |            | other numbers           |                            |                     |
    |____________|_________________________|____________________________|_____________________|
    |            | a 2-dimensional array of|                            |                     |
    |   MATRIX   | numbers                 |             2              |      Upper(M)       |
    |____________|_________________________|____________________________|_____________________|
    |            |a n-dimensional array of |                            |                     |
    |   TENSOR   |numbers                  |             n              |      Upper(T)       |
    |____________|_________________________|____________________________|_____________________|
</pre>
-s.

In [3]:
# 0D Tensor
scalar = torch.tensor(7)
print(scalar)  # print tensor
print(scalar.ndim)  # zero dimension tensor
print(scalar.item())  # get the items of tensor and only work with 0D tensor

tensor(7)
0
7


In [4]:
scalar.ndim

0

In [5]:
## Vector  1D Tensor
vector = torch.tensor([3, 4, 5])
print(vector)  # print 1D tensor
print(vector.ndim)  # get the dimension
# print(vector.item())   # only work with 0D tensor
print(vector.shape)


tensor([3, 4, 5])
1
torch.Size([3])


### **MATRIX and TENSOR**

In [6]:
# 2D tensor
MATRIX = torch.tensor([[2, 3, 4, 5],
                       [2, 4, 6, 8]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[2, 3, 4, 5],
        [2, 4, 6, 8]])
2
torch.Size([2, 4])


In [7]:
import random

In [8]:
# matrix
random.seed(42)
# row2 = list(range(random.randint(0, 9)))   undefined dimension
row1 = [random.randint(0, 9) for x in range(4)]
row2 = [random.randint(0, 9) for x in range(4)]
row3 = [random.randint(0, 9) for x in range(4)]

MATRIX = torch.tensor([row1, row2, row3])
print(MATRIX)  # print tensor
print(MATRIX.ndim)  # get the dimension
print(MATRIX.shape)  # get the shape of tensor

tensor([[1, 0, 4, 3],
        [3, 2, 1, 8],
        [1, 9, 6, 0]])
2
torch.Size([3, 4])


In [9]:
TENSOR = torch.tensor([     # 1
    [                       # 3
        [1, 2, 3, 4],       # 4
        [3, 6, 9, 12],
        [2, 4, 5, 7]
    ]
])

print(TENSOR)  # print tensor
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[ 1,  2,  3,  4],
         [ 3,  6,  9, 12],
         [ 2,  4,  5,  7]]])
3
torch.Size([1, 3, 4])


## **Random Tensor**

In [10]:
rtensor = torch.rand(size=(3, 4))
print(rtensor)
print(rtensor.ndim)
print(rtensor.shape) 
print(rtensor.dtype)

tensor([[0.7869, 0.8865, 0.6503, 0.5826],
        [0.8865, 0.0852, 0.4592, 0.3870],
        [0.3610, 0.5130, 0.8414, 0.1284]])
2
torch.Size([3, 4])
torch.float32


In [11]:

rtensor = torch.rand(size=(3, 7, 7))  # size=(color_channel, height, width)
print(rtensor)
print(rtensor.ndim)
print(rtensor.shape) 
print(rtensor.dtype)

tensor([[[0.5262, 0.9721, 0.3398, 0.8346, 0.5441, 0.3822, 0.3187],
         [0.1329, 0.9270, 0.7346, 0.6328, 0.3424, 0.1266, 0.7477],
         [0.0014, 0.1390, 0.4219, 0.7569, 0.4777, 0.0826, 0.4901],
         [0.5633, 0.2627, 0.1393, 0.6053, 0.9503, 0.2444, 0.7693],
         [0.0424, 0.7458, 0.0832, 0.4547, 0.4367, 0.0541, 0.1834],
         [0.2167, 0.8065, 0.3186, 0.9101, 0.9546, 0.6516, 0.9422],
         [0.7961, 0.1418, 0.5185, 0.1571, 0.0174, 0.4979, 0.9296]],

        [[0.6662, 0.8758, 0.2027, 0.6924, 0.1274, 0.4517, 0.8321],
         [0.6358, 0.3556, 0.1130, 0.4530, 0.1241, 0.4118, 0.4918],
         [0.7017, 0.9474, 0.2712, 0.4362, 0.6006, 0.2905, 0.0304],
         [0.2803, 0.4668, 0.2264, 0.1906, 0.2132, 0.3331, 0.0604],
         [0.0585, 0.2468, 0.2034, 0.4898, 0.3055, 0.0398, 0.6550],
         [0.4484, 0.4400, 0.4767, 0.2077, 0.6067, 0.4448, 0.0908],
         [0.7609, 0.0058, 0.9293, 0.7066, 0.9020, 0.8928, 0.1464]],

        [[0.3557, 0.1069, 0.5027, 0.5780, 0.8844, 0.4472, 

In [12]:
image = torch.rand(size=(12, 8, 3))   # height, width, color_channel
print(image)
print(image.ndim)
print(image.shape) 
print(image.dtype)

tensor([[[0.4492, 0.1785, 0.0402],
         [0.0986, 0.1826, 0.2723],
         [0.4664, 0.2172, 0.4947],
         [0.6871, 0.4398, 0.8055],
         [0.4197, 0.8667, 0.3490],
         [0.8047, 0.9599, 0.3739],
         [0.7391, 0.3195, 0.6888],
         [0.3443, 0.4743, 0.7738]],

        [[0.4006, 0.2916, 0.8581],
         [0.3705, 0.0487, 0.5181],
         [0.6245, 0.6174, 0.9305],
         [0.6535, 0.7430, 0.7035],
         [0.0301, 0.8191, 0.0257],
         [0.2787, 0.1521, 0.0556],
         [0.1417, 0.5555, 0.9695],
         [0.5422, 0.2785, 0.5460]],

        [[0.0769, 0.5897, 0.6287],
         [0.2285, 0.2927, 0.0074],
         [0.4997, 0.2052, 0.6794],
         [0.8592, 0.1738, 0.7004],
         [0.8034, 0.8755, 0.9896],
         [0.1780, 0.2517, 0.1781],
         [0.6621, 0.6259, 0.2730],
         [0.3406, 0.6401, 0.5768]],

        [[0.8643, 0.7463, 0.9645],
         [0.1723, 0.5559, 0.8463],
         [0.4642, 0.7808, 0.2232],
         [0.3417, 0.4167, 0.0989],
         [0.90

### **Zeros and Ones**

In [13]:
zeros = torch.zeros(size=(3, 5), dtype=torch.int)
print(zeros)
print(zeros.dtype)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)
torch.int32


In [14]:
ones = torch.ones(size=(4, 3), dtype=torch.int)
print(ones)
print(ones.dtype)
print(ones.ndim)
print(ones.shape)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
torch.int32
2
torch.Size([4, 3])


### **Creating a range and tesors like**

In [15]:
tsr = torch.range(0, 10)  # may return an error in future
print(tsr)
tsr = torch.arange(0, 10)
print(tsr)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


C:\Users\vikas\AppData\Local\Temp\ipykernel_13764\3208909486.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  tsr = torch.range(0, 10)  # may return an error in future


In [16]:
tsr = torch.arange(0, 11, 2)
tsr

tensor([ 0,  2,  4,  6,  8, 10])

In [17]:
tsr = torch.arange(0, 11, 2, dtype=torch.int)
print(tsr)

tensor([ 0,  2,  4,  6,  8, 10], dtype=torch.int32)


In [18]:
# reshape
tsr.reshape(2, 3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10]], dtype=torch.int32)

### **Tensor Data type**
- There are many different tensor datatypes available in PyTorch. Some are specify for `CPU` and some are better for `GPU`.
- `torch.cuda` is being used for GPU.(NVIDIA GPUs use a computing toolkit called CUDA)
- `torch.float16` or `torch.half`   : 16-bit floating point.
- `torch.float32` or `torch.float`  : 32-bit floating point.
- `torch.float64` or `torch.double` : 64-bit floating point.
- `torch.int16`                     : 16-bit integer point.
- `torch.int` or `torch.int32`      : 32-bit integer point.
- `torch.long` or `torch.int64`     : 64-bit integer point.

In [19]:
tsr = torch.arange(0, 16, 3, dtype=torch.int16)
print(tsr)
tsr = torch.arange(0, 16, 3, dtype=torch.int)
print(tsr)
tsr = torch.arange(0, 16, 3, dtype=torch.long)
print(tsr)
tsr = torch.arange(0, 16, 3, dtype=torch.int32)
print(tsr)
tsr = torch.arange(0, 16, 3, dtype=torch.int64)
print(tsr)

tensor([ 0,  3,  6,  9, 12, 15], dtype=torch.int16)
tensor([ 0,  3,  6,  9, 12, 15], dtype=torch.int32)
tensor([ 0,  3,  6,  9, 12, 15])
tensor([ 0,  3,  6,  9, 12, 15], dtype=torch.int32)
tensor([ 0,  3,  6,  9, 12, 15])


### **Getting information from the tensor**
- __ndim__ : n
- __shape__ : [n, m]
- __dtype__ : int16, int32, int64/long, float16, float32, float64
- __device__ : CPU or GPU

In [20]:
mtx = torch.rand(3, 4)
print(mtx)
print(f"ndim : {mtx.ndim}")
print(f"shpae : {mtx.shape}")
print(f"dtype : {mtx.dtype}")
print(f"device : {mtx.device}")

tensor([[0.7370, 0.1830, 0.0975, 0.9765],
        [0.3790, 0.2703, 0.3898, 0.6402],
        [0.0716, 0.8405, 0.6850, 0.1046]])
ndim : 2
shpae : torch.Size([3, 4])
dtype : torch.float32
device : cpu


### **Manipulating Tensors (tensor operations)**
- Addition : `+` or `torch.add(tensor, tensor)`
- Substraction : `-` or `torch.sub(tensor, tensor)`
- Multiplication (element-wise) : `*` or `torch.mul(tensor, tensor)` or `torch.multiply(tensor, tensor)`   `Condition : t1.shape([p x m]) @ t2shape([m x q]) -> t3.shape([p x q])`
- Division : `/`, `//` or `torch.div(tensor, tensor)`
- Matrix Multiplication : `@` or `torch.matmul(tensor, tensor)` or `torch.mm(tensor, tensor)`
- Modulus : `%`

In [21]:
# Operation with number
tensor = torch.tensor([2, 3, 4])

print(tensor)
print(tensor + 10)  # addition
print(tensor - 2)  # substraction
print(tensor * 5)  # multiplication
print(tensor / 2)  # division
print(tensor // 2) # floor division
print(tensor % 3)  # modulus

print()
print(tensor)
tensor = tensor + 10
print(tensor)
tensor = tensor - 2
print(tensor)
tensor = tensor * 5
print(tensor)
tensor = tensor / 5
print(tensor)
tensor = tensor // 2
print(tensor)
tensor = tensor % 2
print(tensor)

tensor([2, 3, 4])
tensor([12, 13, 14])
tensor([0, 1, 2])
tensor([10, 15, 20])
tensor([1.0000, 1.5000, 2.0000])
tensor([1, 1, 2])
tensor([2, 0, 1])

tensor([2, 3, 4])
tensor([12, 13, 14])
tensor([10, 11, 12])
tensor([50, 55, 60])
tensor([10., 11., 12.])
tensor([5., 5., 6.])
tensor([1., 1., 0.])


In [22]:
tensor = torch.tensor([2, 4, 6, 8, 10])
print(tensor)
print(torch.add(tensor, 10))
print(torch.sub(tensor, 2))
print(torch.mul(tensor, 10))
print(torch.multiply(tensor, 10))
print(torch.div(tensor, 2))

tensor([ 2,  4,  6,  8, 10])
tensor([12, 14, 16, 18, 20])
tensor([0, 2, 4, 6, 8])
tensor([ 20,  40,  60,  80, 100])
tensor([ 20,  40,  60,  80, 100])
tensor([1., 2., 3., 4., 5.])


In [23]:
# Operation on 2 tensor
t1 = torch.tensor([2, 4, 6, 8])
t2 = torch.tensor([1, 2, 3, 4])
print(t1 + t2)
print(t1 - t2)
print(t1 * t2)
print(t1 / t2)
print(t1 % t2)
print(t1 @ t2)
print()

print(torch.add(t1, t2))
print(torch.sub(t1, t2))
print(torch.mul(t1, t2))
print(torch.multiply(t1, t2))
print(torch.div(t1, t2))
print(torch.matmul(t1, t2))
print()

tensor([ 3,  6,  9, 12])
tensor([1, 2, 3, 4])
tensor([ 2,  8, 18, 32])
tensor([2., 2., 2., 2.])
tensor([0, 0, 0, 0])
tensor(60)

tensor([ 3,  6,  9, 12])
tensor([1, 2, 3, 4])
tensor([ 2,  8, 18, 32])
tensor([ 2,  8, 18, 32])
tensor([2., 2., 2., 2.])
tensor(60)



In [24]:
# matrix multiplication
m1 = torch.rand(3, 4)


In [25]:
## calculate time
tensor = torch.tensor([1, 2, 3])
print(tensor.shape)
print("Multiplication : ")
print(tensor * tensor)
print(torch.mul(tensor, tensor))
print()
print("Matrix Multiplication : ")
print(tensor @ tensor)
print(torch.matmul(tensor, tensor))

torch.Size([3])
Multiplication : 
tensor([1, 4, 9])
tensor([1, 4, 9])

Matrix Multiplication : 
tensor(14)
tensor(14)


In [26]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 15.6 ms
Wall time: 6.48 ms


In [27]:
%%time
value = torch.matmul(tensor, tensor)
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 1.01 ms


## <font color="red">**One of the most common errors in deep learning (shape errors)**</font>

In [28]:
t_A = torch.tensor([[1, 2],
                   [3, 4],
                   [5, 6]], dtype=torch.float32)
t_B = torch.tensor([[7, 10],
                   [8, 11],
                   [9, 12]], dtype=torch.float32)
print(t_A, t_B, sep='\n\n', end='\n\n')


tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])



In [29]:
# t_C = torch.matmul(t_A, t_B)     # this will produce error coz t_A(3, 2) and t_B(3, 2)
# print(t_C)

In [30]:
print(t_A, t_B.T, sep="\n\n", end="\n\n")
t_C = torch.matmul(t_A, t_B.T) # take transpose of t_B 
print(t_C)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])


In [31]:
torch.mm(t_A, t_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

### **torch.nn.Linear()**
- **Note** : A matrix multiplication like this is also referred to as the `dot product` of two matrices.
- Nural network are full of matrix multiplications and dot products.
- The `torch.nn.Linear()` module (we'll see this in action later on), also known as a __feed-forward layer__ of __fully connected layer__, implements a matrix multiplication between an input `x` and weights matrix `A`.
- `y = x.transpose(A) + b`
  - Where :
  - `x` is the input to the layer (deep learning is a stack of layers like `torch.nn.Linear()` and others on top of each other.)
  - `A` is the weights matrix created by the layer, this starts out as random numbers that get ajusted as a Neural Netwok learns to better representation patterns in the data. (notice the "`T`", that's because the weights matrix get transposed).
  - __Note__ : You might also often see `W` or another letter like `X` used to showcase the weights matrix.
  - `b` is the bias terms used to slightly offset the weights and inputs.
  - `y` is the output (a manipulation of the input in the hopes to discover patterns in it).
  - This the linear function linek `y = mx + c` equation of straight line. Try to changing the values of `in_features` and `out_features` below and see what happens.
  - Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
  

In [32]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2,   # matche inner dimension of input
                         out_features=6)  # describe outer value

x = torch.tensor([[1, 2],
                  [3, 4],
                  [5, 6]], dtype=torch.float)

output = linear(x)
print(f"Input Shape : {x.shape}\n")
print(f"Output : \n{output}\n\nOuptu Shape : {output.shape}")

Input Shape : torch.Size([3, 2])

Output : 
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Ouptu Shape : torch.Size([3, 6])


In [33]:
torch.manual_seed(32)
linearModel = torch.nn.Linear(in_features=4, # matche inner dimension of input
                         out_features=10) # describe outer value

x = torch.tensor([[1, 2, 3, 4],
                  [2, 4, 6, 8],
                  [3, 6, 9, 12],
                  [4, 8, 12, 16],
                  [5, 10, 15, 20],
                  [6, 12, 18, 24]], dtype=torch.float)

y = linearModel(x)
print(x); print(x.shape); print()
print(y); print(y.shape); print()

tensor([[ 1.,  2.,  3.,  4.],
        [ 2.,  4.,  6.,  8.],
        [ 3.,  6.,  9., 12.],
        [ 4.,  8., 12., 16.],
        [ 5., 10., 15., 20.],
        [ 6., 12., 18., 24.]])
torch.Size([6, 4])

tensor([[  0.4974,  -1.5763,   1.4562,  -0.8506,   0.7215,  -0.4398,  -3.2376,
          -0.5411,   1.0880,   0.6005],
        [  1.3022,  -3.2688,   2.6275,  -1.3393,   1.8976,  -1.1590,  -5.9811,
          -0.7089,   1.9592,   1.3687],
        [  2.1071,  -4.9613,   3.7988,  -1.8280,   3.0737,  -1.8782,  -8.7246,
          -0.8768,   2.8304,   2.1368],
        [  2.9119,  -6.6538,   4.9701,  -2.3167,   4.2497,  -2.5974, -11.4682,
          -1.0447,   3.7016,   2.9050],
        [  3.7168,  -8.3462,   6.1413,  -2.8053,   5.4258,  -3.3166, -14.2117,
          -1.2125,   4.5729,   3.6732],
        [  4.5216, -10.0387,   7.3126,  -3.2940,   6.6019,  -4.0358, -16.9552,
          -1.3804,   5.4441,   4.4413]], grad_fn=<AddmmBackward0>)
torch.Size([6, 10])



### **Finding the min(), max(), mean(), sum(), etc (aggregation)**
- mean() work with only float data type.

In [34]:
x = torch.arange(10, 100, 10)
print(x)
print("Min : ", x.min())
print("Max : ", x.max())
print("Mean : ", x.type(torch.float32).mean()) # work with float dtype
print("Sum : ", x.sum())

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Min :  tensor(10)
Max :  tensor(90)
Mean :  tensor(50.)
Sum :  tensor(450)


In [35]:
print(torch.min(x))
print(torch.max(x))
print(torch.mean(x.type(torch.float32))) # mean work with float dtype
print(torch.sum(x))

tensor(10)
tensor(90)
tensor(50.)
tensor(450)


### **Positional min/max**
- Find the index of a tensor where the max or min value present.
- `torch.argmin()` : return index of min value
- `torch.argmax()` : return inde of max value

In [36]:
tensor = torch.arange(10, 100, 10)
print(f"Tensor : {tensor}")

# Returns index of max and min values
print(f"Max : {tensor.argmax()}")
print(f"Min : {tensor.argmin()}")

Tensor : tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Max : 8
Min : 0


### **Change the data type of tensor**
- `tensor.type(torch.int)`

In [37]:
tsr = torch.arange(10, 100, 7)
print(tsr, tsr.dtype)
print()
print(tsr.type(torch.int32))
print(tsr.type(torch.double))
print(tsr.type(torch.int8))
print(tsr.type(torch.float16))
print(tsr.type(torch.float32))

tensor([10, 17, 24, 31, 38, 45, 52, 59, 66, 73, 80, 87, 94]) torch.int64

tensor([10, 17, 24, 31, 38, 45, 52, 59, 66, 73, 80, 87, 94], dtype=torch.int32)
tensor([10., 17., 24., 31., 38., 45., 52., 59., 66., 73., 80., 87., 94.],
       dtype=torch.float64)
tensor([10, 17, 24, 31, 38, 45, 52, 59, 66, 73, 80, 87, 94], dtype=torch.int8)
tensor([10., 17., 24., 31., 38., 45., 52., 59., 66., 73., 80., 87., 94.],
       dtype=torch.float16)
tensor([10., 17., 24., 31., 38., 45., 52., 59., 66., 73., 80., 87., 94.])


In [38]:
tsr_float = tensor.type(torch.float16)
print(tsr_float)
tsr_int = tensor.type(torch.int8)
print(tsr_int)

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)
tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)


## **<font color="red">Reshaping, stacking, squeezing and unsqueezing</font>**
- `torch.reshape(input, shape)` or `torch.Tensor.reshape()` : Reshape the tensor
- `Tensor.view(shape)` : Return a view of the original tensor in different shape but shares the same data as the original tensor.
- `torch.stack(tensors, dim=0)` : Concatenates a sequence of `tensors` along a new dimension(`dim`), all `tensors` must be same size.
- `torch.squeeze(input)` : Squeezes `input` to remove all the dimensions with value `1`.
- `torch.unsqueeze(input, dim)` : Returns `input` with a dimension value of `1` added at `dim`.
- `torch.permute(input, dims)` : Returns a _view_ of the original `input` with its dimensions permuted(rearranged) to `dims`.

In [39]:
x = torch.tensor(5)   # scaler
x, x.shape, x.ndim

(tensor(5), torch.Size([]), 0)

In [40]:
x = torch.arange(1.0, 8.0)  # vector
x, x.shape, x.ndim

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]), 1)

### **reshape()**

In [41]:
x_reshaped = x.reshape(1, 7)  # matrix
x_reshaped, x_reshaped.shape, x_reshaped.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]), 2)

In [42]:
tsr = torch.arange(2, 31, 2)
tsr, tsr.shape, tsr.ndim

(tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]),
 torch.Size([15]),
 1)

In [43]:
tsr_reshaped = tsr.reshape(3, 5)
tsr_reshaped, tsr_reshaped.shape, tsr_reshaped.ndim

(tensor([[ 2,  4,  6,  8, 10],
         [12, 14, 16, 18, 20],
         [22, 24, 26, 28, 30]]),
 torch.Size([3, 5]),
 2)

In [44]:
tsr = tsr_reshaped.reshape(-1)
tsr, tsr.shape, tsr.ndim

(tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]),
 torch.Size([15]),
 1)

### **view()**

In [45]:
tsr_view = tsr.view(1, 15)
print(tsr_view, tsr.shape, tsr.ndim); print()

tsr_view = tsr.view(3, 5)
print(tsr_view, tsr_view.shape, tsr_view.ndim); print()

tensor([[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]]) torch.Size([15]) 1

tensor([[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20],
        [22, 24, 26, 28, 30]]) torch.Size([3, 5]) 2



### **Slicing**

In [46]:
tsr = tsr.reshape(3, 5)
print(tsr)
mtx = tsr
print()

y = mtx[:, 1:4]  # row, col
print(y); print()


tensor([[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20],
        [22, 24, 26, 28, 30]])

tensor([[ 4,  6,  8],
        [14, 16, 18],
        [24, 26, 28]])



In [47]:
y[:, 0] = 7    # row, col
print(y); print()

y[0, :] = 9    # row, col
print(y); print()

tensor([[ 7,  6,  8],
        [ 7, 16, 18],
        [ 7, 26, 28]])

tensor([[ 9,  9,  9],
        [ 7, 16, 18],
        [ 7, 26, 28]])



In [48]:
z = tsr[1, :]
print(z)

tensor([12,  7, 16, 18, 20])


### **stack()**

In [49]:
# try changing dim to dim=1 and see what happens
tsr_stack = torch.stack([z, z, z, z], dim=0)  # dim=0 for row
print(tsr_stack); print()

tsr_stack = torch.stack([z, z, z, z], dim=1)  # dim=1 for col
print(tsr_stack); print()

tsr_stack = torch.stack([z, z, z, z], dim=-1)  
print(tsr_stack)

tensor([[12,  7, 16, 18, 20],
        [12,  7, 16, 18, 20],
        [12,  7, 16, 18, 20],
        [12,  7, 16, 18, 20]])

tensor([[12, 12, 12, 12],
        [ 7,  7,  7,  7],
        [16, 16, 16, 16],
        [18, 18, 18, 18],
        [20, 20, 20, 20]])

tensor([[12, 12, 12, 12],
        [ 7,  7,  7,  7],
        [16, 16, 16, 16],
        [18, 18, 18, 18],
        [20, 20, 20, 20]])


In [50]:
# slicing in tensor
z = y[1:3 :]
tsr_stack = torch.stack([z, z, z, z], dim=0)
print(z); print()
print(tsr_stack)

tensor([[ 7, 16, 18],
        [ 7, 26, 28]])

tensor([[[ 7, 16, 18],
         [ 7, 26, 28]],

        [[ 7, 16, 18],
         [ 7, 26, 28]],

        [[ 7, 16, 18],
         [ 7, 26, 28]],

        [[ 7, 16, 18],
         [ 7, 26, 28]]])


### **squeeze() or unsqueeze()**
- Removing all single dimensions from a tensor.

In [51]:
matrix = torch.tensor([[2, 4, 6, 8, 10, 12]])
print("matrix : ")
print(matrix, matrix.shape, matrix.ndim); print()

mtx_squeez = matrix.squeeze()
print("mtx_squeez : ")
print(mtx_squeez, mtx_squeez.shape, mtx_squeez.ndim); print()

mtx_unsqueez = matrix.unsqueeze(dim=0)
print("mtx_unsqueez : ")
print(mtx_unsqueez, mtx_unsqueez.shape, mtx_squeez.ndim)

mtx_unsqueez = matrix.unsqueeze(dim=1)
print("mtx_unsqueez : ")
print(mtx_unsqueez, mtx_unsqueez.shape, mtx_squeez.ndim); print()

mtx_unsqueez = matrix.unsqueeze(dim=2)
print("mtx_unsqueez : ")
print(mtx_unsqueez, mtx_unsqueez.shape, mtx_squeez.ndim)

mtx_unsqueez = matrix.unsqueeze(dim=-1)
print("mtx_unsqueez : ")
print(mtx_unsqueez, mtx_unsqueez.shape, mtx_squeez.ndim)



matrix : 
tensor([[ 2,  4,  6,  8, 10, 12]]) torch.Size([1, 6]) 2

mtx_squeez : 
tensor([ 2,  4,  6,  8, 10, 12]) torch.Size([6]) 1

mtx_unsqueez : 
tensor([[[ 2,  4,  6,  8, 10, 12]]]) torch.Size([1, 1, 6]) 1
mtx_unsqueez : 
tensor([[[ 2,  4,  6,  8, 10, 12]]]) torch.Size([1, 1, 6]) 1

mtx_unsqueez : 
tensor([[[ 2],
         [ 4],
         [ 6],
         [ 8],
         [10],
         [12]]]) torch.Size([1, 6, 1]) 1
mtx_unsqueez : 
tensor([[[ 2],
         [ 4],
         [ 6],
         [ 8],
         [10],
         [12]]]) torch.Size([1, 6, 1]) 1


### **permute()**
- You can rearrange the order of axes values with `torch.permute(input, dims)`, where the `input` gets turned into a _view_ with new `dims`.
- Because permuting returns a _view_ (shares the same data as the original), the values in the permuted tensor will be the same as the original tensor and if you change the values in the view, it will change the values of the original.

In [52]:
x_original = torch.arange(1, 106)
# x_original = torch.rand(7, 5, 3)  # [0, 1, 2]
x_original = x_original.reshape(7, 5, 3)   #[0, 1, 2]
print(x_original)
print(x_original.shape, x_original.ndim)
print()
print("-----------------------------------------------------------------")
print()

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 1, 0)   # [2, 1, 0]: shifts axis 0->2, 1->1, 2->0
print(x_permuted)
print(x_permuted.shape, x_original.ndim)
print()
print("-----------------------------------------------------------------")
print()

x_permuted = x_original.permute(2, 0, 1)   #[0, 1, 2] >-->>> [2, 0, 1]
print(x_permuted)
print(x_permuted.shape, x_permuted.ndim)
print()
print("-----------------------------------------------------------------")
print()

x_permuted = x_original.permute(1, 0, 2)
print(x_permuted)
print(x_permuted.shape, x_permuted.ndim)
print()


tensor([[[  1,   2,   3],
         [  4,   5,   6],
         [  7,   8,   9],
         [ 10,  11,  12],
         [ 13,  14,  15]],

        [[ 16,  17,  18],
         [ 19,  20,  21],
         [ 22,  23,  24],
         [ 25,  26,  27],
         [ 28,  29,  30]],

        [[ 31,  32,  33],
         [ 34,  35,  36],
         [ 37,  38,  39],
         [ 40,  41,  42],
         [ 43,  44,  45]],

        [[ 46,  47,  48],
         [ 49,  50,  51],
         [ 52,  53,  54],
         [ 55,  56,  57],
         [ 58,  59,  60]],

        [[ 61,  62,  63],
         [ 64,  65,  66],
         [ 67,  68,  69],
         [ 70,  71,  72],
         [ 73,  74,  75]],

        [[ 76,  77,  78],
         [ 79,  80,  81],
         [ 82,  83,  84],
         [ 85,  86,  87],
         [ 88,  89,  90]],

        [[ 91,  92,  93],
         [ 94,  95,  96],
         [ 97,  98,  99],
         [100, 101, 102],
         [103, 104, 105]]])
torch.Size([7, 5, 3]) 3

---------------------------------------------------

### **Indexing (Selecting data from tensors)**

In [83]:
x = torch.arange(1, 10).reshape(1, 3, 3)  # always use this technique to make tensor
print(x, x.shape, x.ndim); print()

y = x.reshape(-1)
print(y.reshape(3, 3), y.shape, y.ndim); print()   # this technique will give you a tensor but create problem in indexeding and slicing

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3]) 3

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) torch.Size([9]) 1



In [75]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [76]:
y[0]

tensor(1)

In [77]:
x[0][0]

tensor([1, 2, 3])

In [78]:
x[0][0][0]

tensor(1)

In [79]:
x[0,:]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [81]:
y[0:]

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
x[0, 0, 1]

tensor(2)

In [86]:
x[0, 0, :]

tensor([1, 2, 3])

In [87]:
x[0, :, :]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [88]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])