In [1]:
import torch

In [2]:
torch.__version__

'2.1.0'

## **Complexity of Tensor**

### reshape(m, n)

In [3]:
t1 = torch.arange(1, 49).reshape(6, 8)
print(t1)
print(t1.shape, t1.ndim)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32],
        [33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48]])
torch.Size([6, 8]) 2


In [4]:
t1[0]

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
t1[3, 5]

tensor(30)

In [6]:
t1[0][2:5]

tensor([3, 4, 5])

In [7]:
t1[1][1:4]

tensor([10, 11, 12])

In [8]:
t1[:, :][2]

tensor([17, 18, 19, 20, 21, 22, 23, 24])

In [9]:
t1[1:5, 1:5]

tensor([[10, 11, 12, 13],
        [18, 19, 20, 21],
        [26, 27, 28, 29],
        [34, 35, 36, 37]])

In [10]:
t1[1:5, 1:5][2]

tensor([26, 27, 28, 29])

In [11]:
t1[1:5, 1:5][2, 2]

tensor(28)

### reshape(1, m, n)

In [12]:
t2 = torch.arange(1, 49).reshape(1, 6, 8)
print(t2)
print(t2.shape, t2.ndim)

tensor([[[ 1,  2,  3,  4,  5,  6,  7,  8],
         [ 9, 10, 11, 12, 13, 14, 15, 16],
         [17, 18, 19, 20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29, 30, 31, 32],
         [33, 34, 35, 36, 37, 38, 39, 40],
         [41, 42, 43, 44, 45, 46, 47, 48]]])
torch.Size([1, 6, 8]) 3


In [13]:
t2[0]

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32],
        [33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48]])

In [14]:
t2[0][3]

tensor([25, 26, 27, 28, 29, 30, 31, 32])

In [15]:
t2[0][3, 5]

tensor(30)

In [16]:
t2[0][2:5]

tensor([[17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32],
        [33, 34, 35, 36, 37, 38, 39, 40]])

In [17]:
t2[0][2:5, 3:5]

tensor([[20, 21],
        [28, 29],
        [36, 37]])

In [18]:
t2[0][:4, 4:]

tensor([[ 5,  6,  7,  8],
        [13, 14, 15, 16],
        [21, 22, 23, 24],
        [29, 30, 31, 32]])

In [19]:
t2[:,:,:]

tensor([[[ 1,  2,  3,  4,  5,  6,  7,  8],
         [ 9, 10, 11, 12, 13, 14, 15, 16],
         [17, 18, 19, 20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29, 30, 31, 32],
         [33, 34, 35, 36, 37, 38, 39, 40],
         [41, 42, 43, 44, 45, 46, 47, 48]]])

In [20]:
t2[:, 1:5, 1:7] 

tensor([[[10, 11, 12, 13, 14, 15],
         [18, 19, 20, 21, 22, 23],
         [26, 27, 28, 29, 30, 31],
         [34, 35, 36, 37, 38, 39]]])

### reshape(2, m, n)

In [21]:
t3 = torch.arange(1, 49).reshape(2, 6, 4)
print(t3)
print(t3.shape, t3.ndim)

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]],

        [[25, 26, 27, 28],
         [29, 30, 31, 32],
         [33, 34, 35, 36],
         [37, 38, 39, 40],
         [41, 42, 43, 44],
         [45, 46, 47, 48]]])
torch.Size([2, 6, 4]) 3


In [22]:
t3[0, 1:5, :]

tensor([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]])

In [23]:
t3[1, 1:5, :]

tensor([[29, 30, 31, 32],
        [33, 34, 35, 36],
        [37, 38, 39, 40],
        [41, 42, 43, 44]])

In [24]:
t3[:, 1:5, :]

tensor([[[ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16],
         [17, 18, 19, 20]],

        [[29, 30, 31, 32],
         [33, 34, 35, 36],
         [37, 38, 39, 40],
         [41, 42, 43, 44]]])

## **Join Two Tensor**

### reshape(1, m, n)

In [25]:
t_A = torch.arange(1, 10).reshape(1, 3, 3)
t_B = torch.arange(2, 19, 2).reshape(1, 3, 3)
print(t_A, t_A.shape, t_A.ndim); print()
print(t_B, t_B.shape, t_B.ndim); print()
t_C = torch.cat((t_A, t_B))
print(t_C, t_C.shape, t_C.ndim)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3]) 3

tensor([[[ 2,  4,  6],
         [ 8, 10, 12],
         [14, 16, 18]]]) torch.Size([1, 3, 3]) 3

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[ 2,  4,  6],
         [ 8, 10, 12],
         [14, 16, 18]]]) torch.Size([2, 3, 3]) 3


In [26]:
t_C1 = torch.cat((t_A[0], t_B[0]))
print(t_C1, t_C1.shape, t_C1.ndim)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]) torch.Size([6, 3]) 2


In [27]:
t_C2 = torch.cat((t_A, t_B), 0)
print(t_C2, t_C2.shape, t_C2.ndim)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[ 2,  4,  6],
         [ 8, 10, 12],
         [14, 16, 18]]]) torch.Size([2, 3, 3]) 3


In [28]:
t_C3 = torch.cat((t_A, t_B), 1)
print(t_C3, t_C3.shape, t_C3.ndim)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [ 2,  4,  6],
         [ 8, 10, 12],
         [14, 16, 18]]]) torch.Size([1, 6, 3]) 3


In [29]:
t_C5 = torch.cat((t_A, t_B), 2)
print(t_C5, t_C5.shape, t_C5.ndim)

tensor([[[ 1,  2,  3,  2,  4,  6],
         [ 4,  5,  6,  8, 10, 12],
         [ 7,  8,  9, 14, 16, 18]]]) torch.Size([1, 3, 6]) 3


In [30]:
t_C4 = torch.cat((t_A, t_B), -1)
print(t_C4, t_C4.shape, t_C4.ndim)

tensor([[[ 1,  2,  3,  2,  4,  6],
         [ 4,  5,  6,  8, 10, 12],
         [ 7,  8,  9, 14, 16, 18]]]) torch.Size([1, 3, 6]) 3


### reshape(m, n)

In [31]:
t_D = torch.arange(1, 10).reshape(3, 3)
t_E = torch.arange(2, 19, 2).reshape(3, 3)
print(t_D, t_D.shape, t_D.ndim); print()
print(t_E, t_E.shape, t_E.ndim); print()
t_F = torch.cat((t_D, t_E))
print(t_F, t_F.shape, t_F.ndim)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) torch.Size([3, 3]) 2

tensor([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]) torch.Size([3, 3]) 2

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]) torch.Size([6, 3]) 2


In [32]:
t_F1 = torch.cat((t_D, t_E), 0)
print(t_F1, t_F1.shape, t_F1.ndim)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]) torch.Size([6, 3]) 2


In [33]:
t_F2 = torch.cat((t_D, t_E), 1)
print(t_F2, t_F2.shape, t_F2.ndim)

tensor([[ 1,  2,  3,  2,  4,  6],
        [ 4,  5,  6,  8, 10, 12],
        [ 7,  8,  9, 14, 16, 18]]) torch.Size([3, 6]) 2


In [34]:
t_F3 = torch.cat((t_D, t_E), -1)
print(t_F3, t_F3.shape, t_F3.ndim)

tensor([[ 1,  2,  3,  2,  4,  6],
        [ 4,  5,  6,  8, 10, 12],
        [ 7,  8,  9, 14, 16, 18]]) torch.Size([3, 6]) 2


## **PyTorch Tensors & NumPy**
- Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.
- The two main methods you'll want to use for **NumPy Array** -> **PyTorch Tensor**.
  - `torch.from_numpy(ndarray)` - NumPy array -> PyTorch tensor.
  - `torch.Tensor.numpy()` - PyTorch tensor -> NumPy array.

In [35]:
import numpy as np
import torch

### NumPy to Tensor
- `tensor = torch.from_numpy(array)`

In [36]:
array = np.arange(1, 8)
tensor = torch.from_numpy(array)
print(array, type(array))
print(tensor, type(tensor))

[1 2 3 4 5 6 7] <class 'numpy.ndarray'>
tensor([1, 2, 3, 4, 5, 6, 7], dtype=torch.int32) <class 'torch.Tensor'>


In [37]:
arr = np.arange(1.0, 8.0)
print(arr, type(arr), arr.dtype)

tsr = torch.from_numpy(arr).type(torch.float32)  # convert into specific data type
print(tsr, type(tsr), tsr.dtype)

[1. 2. 3. 4. 5. 6. 7.] <class 'numpy.ndarray'> float64
tensor([1., 2., 3., 4., 5., 6., 7.]) <class 'torch.Tensor'> torch.float32


In [38]:
# Changing in array, tensor will be same
# Changing in tensor, array will be same
array = array + 1
tensor = tensor + 2
array, tensor

(array([2, 3, 4, 5, 6, 7, 8]),
 tensor([3, 4, 5, 6, 7, 8, 9], dtype=torch.int32))

### Tensor to NumPy
- `array = tensor.numpy()`

In [39]:
tensor = torch.arange(1, 8)
array = tensor.numpy()
print(tensor, type(tensor), tensor.dtype)
print(array, type(array), array.dtype)

tensor([1, 2, 3, 4, 5, 6, 7]) <class 'torch.Tensor'> torch.int64
[1 2 3 4 5 6 7] <class 'numpy.ndarray'> int64
