# <font color="blue"> **torch.Tensor**</font>
- A complete overview of `torch.tensor()` in this module.
- **torch.Tensor :** A `torch.Tensor` is a multi-dimensional matrix containing elements of a single data type.

## <font color="Red">**Data Types**</font>
- Torch defines 10 tensor types with CPU and GPU variants which are as follows:

<html>
    <body>
        <div>
            <table style="border: 3px solid black;">
                <caption><b>Data Types</b></caption>
                <tr style="border: 2px solid black;">
                    <th style="border: 2px solid black;">Data Type</th>
                    <th style="border: 2px solid black;">dtype</th>
                    <th style="border: 2px solid black;">CPU tensor</th>
                    <th style="border: 2px solid black;">GPU tensor</th>
                </tr>
                <tr style="border: 2px solid black;">
                    <td style="border: 2px solid black;">32-bit floating point</td>
                    <td style="border: 2px solid black; color: red;">torch.float32<br> torch.float</td>
                    <td style="border: 2px solid black; color: red;">torch.FloatTensor</td>
                    <td style="border: 2px solid black; color: red;">torch.cuda.FloatTensor</td>
                </tr>
                <tr style="border: 2px solid black;">
                    <td style="border: 2px solid black;">64-bit floating poin</td>
                    <td style="border: 2px solid black; color: red;">torch.float64<br> torch.double</td>
                    <td style="border: 2px solid black; color: red;">torch.DoubleTensor</td>
                    <td style="border: 2px solid black; color: red;">torch.cuda.DoubleTensor</td>
                </tr>
                <tr style="border: 2px solid black;">
                    <td style="border: 2px solid black;">16-bit floating point 1</td>
                    <td style="border: 2px solid black; color: red;">torch.float16<br> torch.half</td>
                    <td style="border: 2px solid black; color: red;">torch.HalfTensor</td>
                    <td style="border: 2px solid black; color: red;">torch.cuda.HalfTensor</td>
                </tr>
                <tr style="border: 2px solid black;">
                    <td style="border: 2px solid black;">16-bit floating point 2</td>
                    <td style="border: 2px solid black; color: red;">torch.bfloat16</td>
                    <td style="border: 2px solid black; color: red;">torch.BFloat16Tensor</td>
                    <td style="border: 2px solid black; color: red;">torch.cuda.BFloat16Tensor</td>
                </tr>
                <tr>
                    <td style="border: 2px solid black;">32-bit complex</td>
                    <td style="border: 2px solid black; color: red;">torch.complex32<br> torch.chalf</td>
                </tr>
                <tr style="border: 2px solid black;">
                    <td style="border: 2px solid black;">64-bit complex</td>
                    <td style="border: 2px solid black; color: red;">torch.complex64<br> torch.cfloat</td>
                </tr>
                <tr style="border: 2px solid black;">
                    <td style="border: 2px solid black;">128-bit complex</td>
                    <td style="border: 2px solid black; color: red;">torch.complex128<br> torch.cdouble</td>
                </tr>
                <tr style="border: 2px solid black;">
                    <td style="border: 2px solid black;">8-bit integer(unsigned)</td>
                    <td style="border: 2px solid black; color: red;">torch.uint8</td>
                    <td style="border: 2px solid black; color: red;">torch.ByteTensor</td>
                    <td style="border: 2px solid black; color: red;">torch.cuda.ByteTensor</td>
                </tr>
                <tr style="border: 2px solid black;">
                    <td style="border: 2px solid black;">8-bit integer(signed)</td>
                    <td style="border: 2px solid black; color: red;">torch.int8</td>
                    <td style="border: 2px solid black; color: red;">torch.CharTensor</td>
                    <td style="border: 2px solid black; color: red;">torch.cuda.CharTensor</td>
                </tr>
                <tr style="border: 2px solid black;">
                    <td style="border: 2px solid black;">16-bit integer(signed)</td>
                    <td style="border: 2px solid black; color: red;">torch.int16<br> torch.short</td>
                    <td style="border: 2px solid black; color: red;">torch.ShortTensor</td>
                    <td style="border: 2px solid black; color: red;">torch.cuda.ShortTensor</td>
                </tr>
                <tr style="border: 2px solid black;">
                    <td style="border: 2px solid black;">32-bit integer(signed)</td>
                    <td style="border: 2px solid black; color: red;">torch.int32<br> torch.int</td>
                    <td style="border: 2px solid black; color: red;">torch.IntTensor</td>
                    <td style="border: 2px solid black; color: red;">torch.cuda.IntTensor</td>
                </tr>
                <tr style="border: 2px solid black;">
                    <td style="border: 2px solid black;">64-bit integer(signed)</td>
                    <td style="border: 2px solid black; color: red;">torch.int64<br> torch.long</td>
                    <td style="border: 2px solid black; color: red;">torch.LongTensor</td>
                    <td style="border: 2px solid black; color: red;">torch.cuda.LongTensor</td>
                </tr>
                <tr style="border: 2px solid black;">
                    <td style="border: 2px solid black;">Boolean</td>
                    <td style="border: 2px solid black; color: red;">torch.bool</td>
                    <td style="border: 2px solid black; color: red;">torch.BoolTensor</td>
                    <td style="border: 2px solid black; color: red;">torch.cuda.BoolTensor</td>
                </tr>
                <tr style="border: 2px solid black;">
                    <td style="border: 2px solid black;">quantized 8-bit integer (unsigned)</td>
                    <td style="border: 2px solid black; color: red;">torch.quint8</td>
                    <td style="border: 2px solid black; color: red;">torch.ByteTensor</td>
                </tr>
                <tr style="border: 2px solid black;">
                    <td style="border: 2px solid black;">quantized 8-bit integer (signed)</td>
                    <td style="border: 2px solid black; color: red;">torch.qint8</td>
                    <td style="border: 2px solid black; color: red;">torch.CharTensor</td>
                </tr>
                <tr style="border: 2px solid black;">
                    <td style="border: 2px solid black;">quantized 32-bit integer (signed)</td>
                    <td style="border: 2px solid black; color: red;">torch.qint32</td>
                    <td style="border: 2px solid black; color: red;">torch.IntTensor</td>
                </tr>
                <tr style="border: 2px solid black;">
                    <td style="border: 2px solid black;">quantized 4-bit integer (unsigned)</td>
                    <td style="border: 2px solid black; color: red;">torch.quint4x2</td>
                    <td style="border: 2px solid black; color: red;">torch.ByteTensor</td>
                </tr>
            </table>
        </div>
    </body>
</html>

## **Initializing and Basic Operations**
- A tensor can be constructed from a Python `list` or sequence using the `torch.tensor()` constructor:  \
`torch.tensor()` always copies the ***data***. If you have a Tensor ***data*** and just want to change its ***requires_grad*** flag, use `requires_grad()` or `detach()` to avoid a copy. If you hava a ***numpy array*** and want to avoid a copy, use `torch.as_tensor()`.
- A tensor of specific data type can be constructed by passing a `torch.dtype` and / or a `torch.device` to a constructor or tensor creation op : 

In [2]:
import torch
import numpy as np

In [6]:
lst = [[2, 3, 4], [5, 6, 7]]
t1 = torch.tensor(lst)
print(t1); print()

arr = np.array(lst)
t2 = torch.tensor(arr)
print(t2); print()

print(id(lst), id(t1), id(arr), id(t2))
print(type(lst), type(t1), type(arr), type(t2))

tensor([[2, 3, 4],
        [5, 6, 7]])

tensor([[2, 3, 4],
        [5, 6, 7]], dtype=torch.int32)

2942164295680 2942163661360 2942163663824 2942158159312
<class 'list'> <class 'torch.Tensor'> <class 'numpy.ndarray'> <class 'torch.Tensor'>


In [13]:
cpu1 = torch.device('cpu')
t3 = torch.zeros([2, 4], dtype=torch.int32, device=cpu1)
print(t3); print()

if torch.cuda.is_available():
    cuda0 = torch.device('cuda:0')   # raise error coz, there is no GPU setup for PyTorch
    t4 = torch.ones([2, 4], dtype=torch.double, device=cuda0)
    print(t4); print()
else:
    print("No Cuda available in this device."); print()

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

No Cuda available in this device.



In [15]:
torch.device('cpu')

device(type='cpu')

- A tensor can be created with `requires_grad = True` so that `torch.autograd` records operations on them for automatic differentiation.
- Only Tensors of ***floating point*** and ***complex dtype*** can require gradients.

In [40]:
x = torch.tensor([[2, 3], [4, 5]], dtype=torch.float, requires_grad=True)
print(x); print()

p = x.pow(2)
print(p); print()

s = p.sum()
print(s); print()

out = x.pow(2).sum()
out.backward()
print(x.grad)


tensor([[2., 3.],
        [4., 5.]], requires_grad=True)

tensor([[ 4.,  9.],
        [16., 25.]], grad_fn=<PowBackward0>)

tensor(54., grad_fn=<SumBackward0>)

tensor([[ 4.,  6.],
        [ 8., 10.]])


### **Transpose**

In [56]:
# take the transpose of tensor
tsr = torch.tensor([[2, 3, 4, 5],
                    [9, 8, 7, 6],
                    [5, 8, 3, 9]], dtype=torch.int)

print(tsr); print()
print(tsr.T)
print(tsr.mT)
print(tsr.H)
print(tsr.mH)
print()
print(tsr.transpose(0, 1))
print(tsr.transpose(1, 0))
print()
print(tsr.transpose(1, 1))
print(tsr.transpose(0, 0))
print()


tensor([[2, 3, 4, 5],
        [9, 8, 7, 6],
        [5, 8, 3, 9]], dtype=torch.int32)

tensor([[2, 9, 5],
        [3, 8, 8],
        [4, 7, 3],
        [5, 6, 9]], dtype=torch.int32)
tensor([[2, 9, 5],
        [3, 8, 8],
        [4, 7, 3],
        [5, 6, 9]], dtype=torch.int32)
tensor([[2, 9, 5],
        [3, 8, 8],
        [4, 7, 3],
        [5, 6, 9]], dtype=torch.int32)
tensor([[2, 9, 5],
        [3, 8, 8],
        [4, 7, 3],
        [5, 6, 9]], dtype=torch.int32)

tensor([[2, 9, 5],
        [3, 8, 8],
        [4, 7, 3],
        [5, 6, 9]], dtype=torch.int32)
tensor([[2, 9, 5],
        [3, 8, 8],
        [4, 7, 3],
        [5, 6, 9]], dtype=torch.int32)

tensor([[2, 3, 4, 5],
        [9, 8, 7, 6],
        [5, 8, 3, 9]], dtype=torch.int32)
tensor([[2, 3, 4, 5],
        [9, 8, 7, 6],
        [5, 8, 3, 9]], dtype=torch.int32)



### **Tensor Properties**
- Accessing this property is equivalent to calling `adjoint()`.

https://pytorch.org/docs/stable/tensors.html#torch-tensor