In [3]:
import numpy as np

### **<h3 style="color:red">Tensorflow</h3>**
- tensorflow is a container for numbers.
- matrix is like tensor
### **<h4 style="color:green">0D Tensor/Scalar</h4>**
- 2, 3, zero dimensin tensor
- Tensor and 1D array are same things.
### **<h4 style="color:green">1D Tensor</h4>**
- [1, 2, 3, 4] : 1D tensor, vector(4D), 1D array
- ndim = 1
- Axis in Tensor : Dimension
- **Vector** : addition of scaler will form vector. eg. : [1, 2, 3] = 3D vector, [1, 2, 3, 4] = 4D vector
### **<h4 style="color:green">2D Tensor</h4>**
- [1, 2, 3], [4, 5, 6], [7, 8, 9]
- Rank = 2 = ndim
- [[1 2 3]\
 [4 5 6]\
 [7 8 9]]
### **<h4 style="color:green">ND Tensor</h4>**
- [[[1, 2, 3], [2, 3, 4], [3, 4, 5]],
   [[5, 6, 7], [5, 3, 2], [8, 4, 3]],
   [[4, 5, 6], [7, 5, 3], [4, 3, 2]]

### **<h4 style="color:blue">Rank, Axes and Shape</h4>**
- No. of Axis = Rank = No. of dimension(dim)
- Shape = (row, col)
- Size = row*col

In [8]:
# 0D tensor
a = np.array(4)
print(a)
print(a.shape)
print(a.size)

4
()
1


In [9]:
# 1D tensor
arr = np.array([1, 2, 3, 4])
print(arr)
print(arr.ndim)
# it is also a vector whose dimension is 4D

[1 2 3 4]
1


In [14]:
# 2D tensor
ar = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(ar)
print(ar.shape)
print(ar.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2


**Student_details.csv**
- It have columns = [CGPA, IQ, State][Placement]
- State : UP = 1, wB = 0
#### **1D Tensor**
- [8.2, 99, 0] ----> 1D Tensor and 3D Vector
#### **2D Tensor**
- Collection of 1D tensor form 2D tensor
- [[3.9, 45, 1]\
  [7.8, 78, 0]\
  [9.8, 89, 1]]
#### **3D Tensor**
- Collection of 2D tensor form 3D tensor
#### **4D Tensor**
- Collection of 3D tensor from 4D tensor
- Image is a example of 4D tensor
#### **5D Tensor**
- Videos are example of 5D tensor

In [15]:
import pandas as pd

In [18]:
df = pd.read_csv("../data/train/aug_train.csv")
df

enrollee_id      city  city_development_index gender  \
0             8949  city_103                   0.920   Male   
1            29725   city_40                   0.776   Male   
2            11561   city_21                   0.624    NaN   
3            33241  city_115                   0.789    NaN   
4              666  city_162                   0.767   Male   
...            ...       ...                     ...    ...   
19153         7386  city_173                   0.878   Male   
19154        31398  city_103                   0.920   Male   
19155        24576  city_103                   0.920   Male   
19156         5756   city_65                   0.802   Male   
19157        23834   city_67                   0.855    NaN   

           relevent_experience enrolled_university education_level  \
0      Has relevent experience       no_enrollment        Graduate   
1       No relevent experience       no_enrollment        Graduate   
2       No relevent experience    Full time course        Graduate   
3       No relevent experience                 NaN        Graduate   
4      Has relevent experience       no_enrollment         Masters   
...                        ...                 ...             ...   
19153   No relevent experience       no_enrollment        Graduate   
19154  Has relevent experience       no_enrollment        Graduate   
19155  Has relevent experience       no_enrollment        Graduate   
19156  Has relevent experience       no_enrollment     High School   
19157   No relevent experience       no_enrollment  Primary School   

      major_discipline experience company_size    company_type last_new_job  \
0                 STEM        >20          NaN             NaN            1   
1                 STEM         15        50-99         Pvt Ltd           >4   
2                 STEM          5          NaN             NaN        never   
3      Business Degree         <1          NaN         Pvt Ltd        never   
4                 STEM        >20        50-99  Funded Startup            4   
...                ...        ...          ...             ...          ...   
19153       Humanities         14          NaN             NaN            1   
19154             STEM         14          NaN             NaN            4   
19155             STEM        >20        50-99         Pvt Ltd            4   
19156              NaN         <1      500-999         Pvt Ltd            2   
19157              NaN          2          NaN             NaN            1   

       training_hours  target  
0                  36     1.0  
1                  47     0.0  
2                  83     0.0  
3                  52     1.0  
4                   8     0.0  
...               ...     ...  
19153              42     1.0  
19154              52     1.0  
19155              44     0.0  
19156              97     0.0  
19157             127     0.0  

[19158 rows x 14 columns]

In [20]:
df.columns

Index(['enrollee_id', 'city', 'city_development_index', 'gender',
       'relevent_experience', 'enrolled_university', 'education_level',
       'major_discipline', 'experience', 'company_size', 'company_type',
       'last_new_job', 'training_hours', 'target'],
      dtype='object')

In [21]:
df.describe()

enrollee_id  city_development_index  training_hours        target
count  19158.000000            19158.000000    19158.000000  19158.000000
mean   16875.358179                0.828848       65.366896      0.249348
std     9616.292592                0.123362       60.058462      0.432647
min        1.000000                0.448000        1.000000      0.000000
25%     8554.250000                0.740000       23.000000      0.000000
50%    16982.500000                0.903000       47.000000      0.000000
75%    25169.750000                0.920000       88.000000      0.000000
max    33380.000000                0.949000      336.000000      1.000000

In [23]:
df.isnull().sum()

enrollee_id                  0
city                         0
city_development_index       0
gender                    4508
relevent_experience          0
enrolled_university        386
education_level            460
major_discipline          2813
experience                  65
company_size              5938
company_type              6140
last_new_job               423
training_hours               0
target                       0
dtype: int64