## **Production Code**

In [1]:
import pickle
import numpy as np

In [2]:
ohe_sex = pickle.load(open('../models/ohe_sex.pkl', 'rb'))
ohe_embarked = pickle.load(open('../models/ohe_embarked.pkl', 'rb'))
clf = pickle.load(open('../models/clf.pkl', 'rb'))

In [3]:
# Assume user input
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'], dtype=object).reshape(1, 7)
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [4]:
test_input_sex = ohe_sex.transform(test_input[:, 1].reshape(1, 1))
test_input_sex

/home/arjun/anaconda3/envs/Project_01/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 1.]])

In [5]:
test_input_embarked = ohe_embarked.transform(test_input[:, -1].reshape(1, 1))
test_input_embarked

array([[0., 0., 1.]])

In [6]:
test_input_age = test_input[:,2].reshape(1, 1)
test_input_age

array([[31.0]], dtype=object)

In [7]:
test_input_transformed = np.concatenate((test_input[:, [0, 3, 4, 5]], test_input_age, test_input_sex, test_input_embarked), axis=1)
test_input_transformed

array([[2, 0, 0, 10.5, 31.0, 0.0, 1.0, 0.0, 0.0, 1.0]], dtype=object)

In [8]:
y = clf.predict(test_input_transformed)
y

/home/arjun/anaconda3/envs/Project_01/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1.])